kind: Deployment
apiVersion: apps/v1
metadata:
  name: createorder
spec:
  # A deployment's specification really only 
  # has a few useful options
  # 1. How many copies of each pod do we want?
  replicas: 3

  # 2. How do want to update the pods?
  #strategy: Recreate

  # 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      app: createorder
  # This template field is a regular pod configuration 
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        app: createcorder
    spec:
      containers:
        - name: createcorder
          image: anirudhya/create_order:latest
          ports: 
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: createcorder-service
spec:
  selector:
    app: createcorder
  ports:
  - protocol: "TCP"
    port: 5002
    targetPort: 5000
  type: LoadBalancer
